// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0_m1uG98K6Anhm1hmbDFAfiYrVHIcsg',
    appId: '1:844039241960:web:4c843766e59c8c7a27095d',
    messagingSenderId: '844039241960',
    projectId: 'twitter-app-f3f03',
    authDomain: 'twitter-app-f3f03.firebaseapp.com',
    storageBucket: 'twitter-app-f3f03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo4C9_fA4zn5HxsTrcjBqm6hLlE69eKxk',
    appId: '1:844039241960:android:f6b59ef8d231dba627095d',
    messagingSenderId: '844039241960',
    projectId: 'twitter-app-f3f03',
    storageBucket: 'twitter-app-f3f03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpnzOJrs6usbpjku2JxNcnl3zqrCUM4Zs',
    appId: '1:844039241960:ios:9ad9551f69d1b86027095d',
    messagingSenderId: '844039241960',
    projectId: 'twitter-app-f3f03',
    storageBucket: 'twitter-app-f3f03.appspot.com',
    iosClientId: '844039241960-u56mfvqe5podo86frtao8p61q2iud4g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpnzOJrs6usbpjku2JxNcnl3zqrCUM4Zs',
    appId: '1:844039241960:ios:6ef614764d969d1c27095d',
    messagingSenderId: '844039241960',
    projectId: 'twitter-app-f3f03',
    storageBucket: 'twitter-app-f3f03.appspot.com',
    iosClientId: '844039241960-v0ni2llpa2j8cl6do9r39un76lg41fqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
